# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  MIGRATIONS_PATH: database/migrations

dotenv: ['.env']

tasks:
  default:
    silent: true
    cmds:
      - |
        echo "🚀 Go Test Assignment: Subscription Service API"
        echo "   REST service for managing user subscriptions"
        echo ""
        echo "📖 Available commands: task --list"
        echo "   Documentation: README.md"

  env:
    desc: "Print .env file variables"
    silent: true
    cmds:
      - echo DB_PORT={{.DB_PORT}}
      - echo DB_HOST={{.DB_HOST}}
      - echo DB_USER={{.DB_USER}}
      - echo DB_PASS={{.DB_PASS}}
      - echo DB_NAME={{.DB_NAME}}
      - echo DB_URL={{.DB_URL}}
      - echo DB_TEST_URL={{.DB_TEST_URL}}

  docker:up:
    desc: "Run docker compose fleet"
    aliases: [up, serve]
    cmds:
      - docker compose up {{.CLI_ARGS}}

  app:sh:
    desc: "Run application server shell"
    aliases: [sh]
    cmds:
      - docker compose exec -it app sh

  app:compile:
    desc: "Compile application"
    aliases: [compile]
    cmds:
      - go build -o target/server cmd/server/main.go

  app:build:
    desc: "Build application"
    deps: [app:test]
    aliases: [build]
    cmds:
      - go build -o target/server cmd/server/main.go

  app:test:
    desc: "Run application test"
    deps: [migrate:test:fresh]
    aliases: [test]
    cmds:
      - go test ./models/ ./tests/... {{.CLI_ARGS}}

  app:testsum:
    desc: "Run application test"
    deps: [migrate:test:fresh]
    aliases: [testsum]
    cmds:
      - gotestsum ./models/ ./tests/... {{.CLI_ARGS}}

  pg:sh:
    desc: "Run PostreSQL shell"
    aliases: [pg]
    cmds:
      - docker compose exec -it postgres psql -U postgres

  boiler:config:
    desc: "Generate SQLBoiler config file"
    silent: true
    cmds:
      - |
        cat > sqlboiler.toml << EOF
        output   = "models"
        wipe     = true
        no-tests = false
        add-enum-types = true

        [psql]
          dbname = "{{.DB_NAME}}"
          host   = "{{.DB_HOST}}"
          port   = {{.DB_PORT}}
          user   = "{{.DB_USER}}"
          pass   = "{{.DB_PASS}}"
          sslmode = "disable"
          blacklist = ["schema_migrations"]
        EOF

  boiler:models:
    desc: "Generate SQLBoiler models"
    deps: [boiler:config]
    cmds:
      - sqlboiler psql --output internal/models

  boiler:factories:
    desc: "Generate SQLBoiler factories"
    deps: [boiler:config]
    cmds:
      - boilingfactory psql --sqlboiler-models github.com/zeleniy/test28/internal/models --output database/factories --wipe

  boiler:seeders:
    desc: "Generate SQLBoiler factories"
    deps: [boiler:config]
    cmds:
      - boilingseed psql --sqlboiler-models github.com/zeleniy/test28/internal/models --pkgname seeders --output database/seeders --wipe

  boiler:code:
    desc: "Generate ORM entities"
    deps: [boiler:models, boiler:factories, boiler:seeders]

  db:seed:
    desc: "Seed database with some data"
    deps: [boiler:code]
    aliases: [seed]
    cmds:
      - go run cmd/seed/main.go

  db:test:wipe:
    desc: "Drop all tables"
    cmds:
      - psql {{.DB_TEST_URL}} -c "
          DO \$\$ 
          DECLARE 
              r RECORD;
          BEGIN
              FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') 
              LOOP
                  EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
              END LOOP;
          END \$\$;"

  migrate:up:
    desc: "Apply migrations"
    cmds:
      - migrate -database '{{.DB_URL}}' -path {{.MIGRATIONS_PATH}} up {{.CLI_ARGS}}

  migrate:down:
    desc: "Rollback migrations" 
    cmds:
      - migrate -database '{{.DB_URL}}' -path {{.MIGRATIONS_PATH}} down {{.CLI_ARGS}}

  migrate:version:
    desc: "Show current migration version"
    cmds:
      - migrate -database '{{.DB_URL}}' -path {{.MIGRATIONS_PATH}} version {{.CLI_ARGS}}

  migrate:test:up:
    desc: "Apply migrations"
    cmds:
      - migrate -database '{{.DB_TEST_URL}}' -path {{.MIGRATIONS_PATH}} up {{.CLI_ARGS}}

  migrate:test:down:
    desc: "Rollback migrations" 
    cmds:
      - migrate -database '{{.DB_TEST_URL}}' -path {{.MIGRATIONS_PATH}} down {{.CLI_ARGS}}

  migrate:test:version:
    desc: "Show current migration version"
    cmds:
      - migrate -database '{{.DB_TEST_URL}}' -path {{.MIGRATIONS_PATH}} version {{.CLI_ARGS}}

  migrate:test:fresh:
    desc: "Drop all tables and re-run all migrations"
    cmds:
      - task: db:test:wipe
      - task: migrate:test:up

  migrate:test:refresh:
    desc: "Reset and re-run all migrations"
    cmds:
      - task: migrate:test:down
      - task: migrate:test:up
