# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  MIGRATIONS_PATH: db/migrations

dotenv: ['.env']

tasks:
  default:
    silent: true
    cmds:
      - |
        echo "🚀 Go Test Assignment: Subscription Service API"
        echo "   REST service for managing user subscriptions"
        echo ""
        echo "📖 Available commands: task --list"
        echo "   Documentation: README.md"

  env:
    desc: "Print .env file variables"
    silent: true
    cmds:
      - echo DB_PORT={{.DB_PORT}}
      - echo DB_HOST={{.DB_HOST}}
      - echo DB_USER={{.DB_USER}}
      - echo DB_PASS={{.DB_PASS}}
      - echo DB_NAME={{.DB_NAME}}

  docker:up:
    desc: "Run docker compose fleet"
    aliases: [up, serve]
    cmds:
      - docker compose up {{.CLI_ARGS}}

  app:sh:
    desc: "Run application server shell"
    aliases: [sh]
    cmds:
      - docker compose exec -it app sh

  app:test:
    desc: "Run application test"
    aliases: [test]
    cmds:
      - go test ./models

  boiler:config:
    desc: "Generate SQLBoiler config file"
    cmds:
      - |
        cat > sqlboiler.toml << EOF
        output   = "models"
        wipe     = true
        no-tests = false
        add-enum-types = true

        [psql]
          dbname = "{{.DB_NAME}}"
          host   = "{{.DB_HOST}}"
          port   = {{.DB_PORT}}
          user   = "{{.DB_USER}}"
          pass   = "{{.DB_PASS}}"
          sslmode = "disable"
          blacklist = ["schema_migrations"]
        EOF

  boiler:models:
    desc: "Generate SQLBoiler models"
    deps: [boiler:config]
    cmds:
      - sqlboiler psql

  migrate:up:
    desc: "Apply migrations"
    cmds:
      - migrate -database 'postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable' -path {{.MIGRATIONS_PATH}} up {{.CLI_ARGS}}

  migrate:down:
    desc: "Rollback migrations" 
    cmds:
      - migrate -database 'postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable' -path {{.MIGRATIONS_PATH}} down {{.CLI_ARGS}}

  migrate:version:
    desc: "Show current migration version"
    cmds:
      - migrate -database 'postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable' -path {{.MIGRATIONS_PATH}} version {{.CLI_ARGS}}
